### ISSUE TITLE
myfreecams.py for streamlink 

### ISSUE THREAD

**Issue by ckazkackazi** [Damianonymous/streamlink-plugins#1]
myfreecams.py for streamlink now is not working properly, the stream is written in small pieces, please update

**Comment by Damianonymous** [comment]
How small are these pieces? Earlier you worked well? I tried a few models and I think it still works.

<a href='https://postimg.cc/q6g6dYHh' target='_blank'><img src='https://i.postimg.cc/q6g6dYHh/mfc.jpg' border='0' alt='mfc'/></a>

**Comment by ckazkackazi** [comment]
I changed the quality from "best" to "600p" and everything was fine
make please plugin and for site stripchat
thank you and happy new year

**Comment by Damianonymous** [comment]
It's possible that this is a streamlink version, I'm using a development release. I do not know if the stable version supports these commands, but in the latest version you can use stream exclusion `--stream-sorting-excludes=960p`  or  `streamlink --stream-sorting-excludes '>=600p' URL best,best-unfiltered`
