### ISSUE TITLE
chaturbate.py plugin

### ISSUE THREAD

**Issue by acp164** [Damianonymous/streamlink-plugins#10]
How can i change this plugin to work on cosplayercam.com site? same site with chaturbate but just url is different i guess

**Comment by Damianonymous** [comment]
Use the generic plugin that supports multiple pages, I added it to the archive, plugin is still updated on author's site.

**Comment by wiemar7** [comment]
@Damianonymous podaj maila. mam wtyczki do cam4 i chaturbate na streamlink 2.0

**Comment by Damianonymous** [comment]
@ Showup działa w wersji 2.0

**Comment by Damianonymous** [comment]
> @Damianonymous podaj maila. mam wtyczkę do chaturbate na streamlink 2.0. cam4 i showup nie działa

Wtyczka Showup działa w wersji 2.0. Do Chaturbate i cam4 wystarczy wtyczka generic.py.
