### ISSUE TITLE
bongacams.py broken

### ISSUE THREAD

**Issue by SnowManWithCarrot** [Damianonymous/streamlink-plugins#17]
got broken yesterday

`[cli][error] Unable to validate result: Unable to validate key 'status': 'error' does not equal 'success'`

**Comment by Ptibouc77** [comment]
I can confirm this
`[cli][error] Unable to validate result: Unable to validate key 'status': 'error' does not equal 'success'`

**Comment by Damianonymous** [comment]
These issues are still there, is everything back to normal?

**Comment by SnowManWithCarrot** [comment]
@Damianonymous they're still here :)

@nxkbd was working on a fix as far as I saw

**Comment by Ptibouc77** [comment]
I don't know why but today i can record Bongacams

**Comment by SnowManWithCarrot** [comment]
@Damianonymous You are right - I replaced mine with the old one and it works.

Guess they changed the cookies back to how they was :)
