### ISSUE TITLE
Camsoda no sound

### ISSUE THREAD

**Issue by nixnix999** [Damianonymous/streamlink-plugins#18]
I'm using camsoda.py which some of you guys fixed just like two weeks ago and it worked just fine until two days ago... Seems like they changed something on camsoda two days ago and now all my new videos with recorded models from that site are no sound. I don't know where's a problem, I don't get any error when I'm recording but all my new videos with different models are no sound. I know one more guy who has the same problem, so it's not just me... Hope someone can fix it.

**Comment by Damianonymous** [comment]
It should work, call me if I broke something ;)

**Comment by nixnix999** [comment]
THX!
