### ISSUE TITLE
Add support for flirt4free

### ISSUE THREAD

**Issue by Hunterek** [Damianonymous/streamlink-plugins#2]
Can you add flirt4free ex valid links

> https://manifest.vscdns.com/chunklist.m3u8?model_id=796783&host=wowza-transcode001.rs-tx.vs3.com&provider=edgecast&secure=true

Cheers

**Comment by Damianonymous** [comment]
Sorry, my files are just archives from removed repositories. Change the video player on this site to Flash, copy the link using, for example, Internet Download Manager and use it with IDM, Streamlink, RTMPDump etc.

rtmp://wowza-edge002.vs3.com/liveEdge/885817-wowza-transcode002.rs-tx.vs3.com.f4v/mp4:885817-wowza-transcode002.rs-tx.vs3.com.f4v

**Comment by Damianonymous** [comment]
Sorry, my files are just archives from removed repositories. Change the video player on this site to Flash, copy the link using, for example, Internet Download Manager and use it with IDM, Streamlink, RTMPDump etc.

[rtmp://wowza-edge002.vs3.com/liveEdge/885817-wowza-transcode002.rs-tx.vs3.com.f4v/mp4:885817-wowza-transcode002.rs-tx.vs3.com.f4v](url)
