### ISSUE TITLE
Cam4: "error: No playable streams found on this URL"

### ISSUE THREAD

**Issue by DerpDicler** [Damianonymous/streamlink-plugins#20]
Hello,

I noticed the Cam4 plugin has not been updated in 3 years so I'm not surprised it doesn't appear to be working but wanted to make sure. When I try to load a URL from the site I only get the message "error: No playable streams found on this URL"

Is there a chance the plugin may be updated in the future or is it no longer being maintained? Thanks.

**Comment by Damianonymous** [comment]
It is possible that someone updates the plug or finds a fix on the internet and shares it with us. It is difficult to say when this will happen.

**Comment by Damianonymous** [comment]
Update added.
