### ISSUE TITLE
Camsoda plugin can't open stream

### ISSUE THREAD

**Issue by CosminC3** [Damianonymous/streamlink-plugins#22]
Hi,

I have the same problem as in https://github.com/Damianonymous/streamlink-plugins/issues/15
I noticed nobody commented or tried to find a fix...
![Clipboard02](https://user-images.githubusercontent.com/83722410/152404019-b1b72432-e881-4964-858b-2a05612e8942.jpg)

Late edit

Question: "==" from the end of the link might have something to do with this problem?

**Comment by joss39** [comment]
hello, replace the code

HLS_URL_VIDEO_EDGE = "https://{server}/{stream_name}_h264_aac_720p/index.m3u8?token={token}"
for
HLS_URL_VIDEO_EDGE = "https://{server}/{stream_name}_v1/index.m3u8?token={token}"

**Comment by CosminC3** [comment]
It works fine now.
Thank you very much.

Looks like they changed the url...
If it happens again where I can find this url -so I can change it in the plugin?
