### ISSUE TITLE
Suggestion: logging

### ISSUE THREAD

**Issue by CosminC3** [Damianonymous/streamlink-plugins#23]
Hi,

How about logging the events with the models - in the plugins?
I see there is self.logger but I'm not sure it can be used for this.
File name: log_modelname_servername.txt
If the file exists the new info will be added at the end.
Example:
[curdatetime]
Starting session
[curdatetime]  //model is online and broadcasting
Trying to connect...
[curdatetime]
Connection successful or not successful.
And so on...

Since you can't stay all the time in front of the computer this will be very useful.

If you don't have time, I could write the code and all you have to do is adding  to the plugins...

Thank you.

**Comment by Damianonymous** [comment]
I'm just an archivist of old plugins and programs. If you have time for such fun, we can test your work ;)

**Comment by CosminC3** [comment]
Hi,

Very sorry for not doing what I promised.
I had so many problems to solve in my private life (mostly money and health).

Here is the first version.
Probably it has a few bugs and/or it can be improved.
So I wait your comments...

Offtopic: I have been working on another feature but so far I only get this error: "error: Failed to parse playlist: Missing #EXTM3U header".
I won't explain what is it  - maybe after I will make it work...

Thank you.
[chaturbate.zip](https://github.com/Damianonymous/streamlink-plugins/files/9618898/chaturbate.zip)
