### ISSUE TITLE
mfc

### ISSUE THREAD

**Issue by nadsugifka** [Damianonymous/streamlink-plugins#3]
Hello
pls check the myfreecams.py plugin it does not work (streamlink-plugins)

**Comment by Damianonymous** [comment]
Can you provide more details? It seems that it still works without problems.

<a href='https://postimg.cc/7bQdD9Mv' target='_blank'><img src='https://i.postimg.cc/7bQdD9Mv/MFC2.jpg' border='0' alt='MFC2'/></a>

**Comment by nadsugifka** [comment]
didn't work 3 days, now works, maybe had problems with my VPN, sorry
