### ISSUE TITLE
showup

### ISSUE THREAD

**Issue by Doodik** [Damianonymous/streamlink-plugins#4]
привет, вчера были изменения на showup, плагин перестал работать

**Comment by Doodik** [comment]
интересно, автор ещё тут?

**Comment by Damianonymous** [comment]
Плагин работает без каких-либо изменений. Если вы использовали Recorder, я сделал небольшую поправку.

**Comment by Doodik** [comment]
Да спасибо!
А можно плагин написать под https://livacha.com ? Спасибо

**Comment by Damianonymous** [comment]
Вы можете записать с помощью IDM или загрузить ссылку FLV в Streamlink, например:

`streamlink rtmp://4.livacha.com:1937/live_flash//hlizfxx_49413_29406?vhost=live_flash best -o video.flv`

**Comment by Doodik** [comment]
Увы, это разовая история, не подходит. А с плагином я бы мог автоматизировать процес.
