### ISSUE TITLE
mfc 

### ISSUE THREAD

**Issue by nadsugifka** [Damianonymous/streamlink-plugins#6]
Hello!
Mfc not record, error, please check and fix it
![mfc-er](https://user-images.githubusercontent.com/48850500/88039485-d3993e80-cb71-11ea-8c15-0918f65fc08a.jpg)

**Comment by jdoedev123** [comment]
Here is a working version of the  streamlink plugin based on the changes made to the kodi plugin.
[myfreecams.py.zip](https://github.com/Damianonymous/streamlink-plugins/files/5235446/myfreecams.py.zip)
